// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAuyzRVpWKssl5MO5yqLdpXcmdeutsX60',
    appId: '1:241083359942:web:42a776ffea5effcd8e2dc7',
    messagingSenderId: '241083359942',
    projectId: 'pushnoti-14d01',
    authDomain: 'pushnoti-14d01.firebaseapp.com',
    storageBucket: 'pushnoti-14d01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzmblavYb3cLE1hxYNyqJD9xJ0tEGe8o',
    appId: '1:241083359942:android:241ac6ae86fa8ee38e2dc7',
    messagingSenderId: '241083359942',
    projectId: 'pushnoti-14d01',
    storageBucket: 'pushnoti-14d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYNAHP2z1is7wV037et6O8BS7FoVy9tXA',
    appId: '1:241083359942:ios:1058e3446c0789628e2dc7',
    messagingSenderId: '241083359942',
    projectId: 'pushnoti-14d01',
    storageBucket: 'pushnoti-14d01.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYNAHP2z1is7wV037et6O8BS7FoVy9tXA',
    appId: '1:241083359942:ios:1058e3446c0789628e2dc7',
    messagingSenderId: '241083359942',
    projectId: 'pushnoti-14d01',
    storageBucket: 'pushnoti-14d01.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
